global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:4000']

  - job_name: 'worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:9102'] 